# Generated by Django 4.0.3 on 2022-04-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('middle_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('street', models.CharField(max_length=264)),
                ('state', models.CharField(max_length=264)),
                ('city', models.CharField(max_length=264)),
                ('phone', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=264)),
            ],
        ),
    ]
