# Generated by Django 4.0.3 on 2022-04-09 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_name_contact_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='total',
        ),
    ]
